Updated apiVersion to be supported by kube 1.16 api - WAITING ON COUCHDB
ibm-cloud-architecture/refarch-cloudnative-micro-customer pull request #97
Opened 2019-10-01 21:10 UTC by jjvilleg

2019-10-01 21:12 UTC, evie-lau requested changes
We'll also need the `spec.selector.matchLabel` field, and a 0.1.1 helm release

2019-10-03 19:27 UTC, jjvilleg commented
Couldn't find original issue, so created a new one to track on the couchdb helm chart page. 
https://github.com/helm/charts/issues/17680

2019-10-04 15:33 UTC, evie-lau submitted a review, later dismissed

2019-11-04 15:39 UTC, jjvilleg commented
Ready to be merged @kevinwlau

2019-11-04 21:58 UTC, evie-lau requested changes

2019-11-04 21:58 UTC, kevinwlau commented on chart/release/index.yaml
> +    created: 2019-10-03T13:14:16.525064-05:00
Need to re-index the helm repo with the new 0.1.1 tar file

2019-11-05 17:02 UTC, evie-lau approved these changes

2019-11-05 21:08 UTC, merged